services:
  management-web-astro:
    build:
      context: .
      dockerfile: apps/management-web-astro/Dockerfile
    restart: unless-stopped
    ports:
      - "3916:3000"
    volumes:
      - db-data:/data
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/db.sqlite
      - NODE_ENV=production
    depends_on:
      redirect-service:
        condition: service_started

  redirect-service:
    build:
      context: .
      dockerfile: apps/redirect-service/Dockerfile
    restart: unless-stopped
    ports:
      - "8915:8000"
    volumes:
      - db-data:/data
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/db.sqlite
      - NODE_ENV=production

volumes:
  db-data:
    driver: local
